#!/usr/bin/env python

import argparse, sys
from argparse import RawTextHelpFormatter
import math

__author__ = "Author (email@site.com)"
__version__ = "$Revision: 0.0.1 $"
__date__ = "$Date: 2013-05-09 14:31 $"

# --------------------------------------
# define functions

def get_args():
    parser = argparse.ArgumentParser(formatter_class=RawTextHelpFormatter, description="\
pythonTemplate.py\n\
author: " + __author__ + "\n\
version: " + __version__ + "\n\
description: Basic python script template")
    parser.add_argument('n', type=int, help='choose from n items')
    parser.add_argument('k', type=int, help='choose k items from n with replacement')
    parser.add_argument('-l', '--log', action='store_true', help='report log10 of value')

    # parse the arguments
    args = parser.parse_args()

    # send back the user input
    return args

def log_choose(n, k, log):
    r = 0.0

    # swap for efficiency if k is more than half of n
    if k * 2 > n:
        k = n - k

    for  d in xrange(1,k+1):
        r += math.log(n, 10)
        r -= math.log(d, 10)
        n -= 1

    if log:
        return r
    else:
        return 10**r

# --------------------------------------
# main function

def main():
    # parse the command line args
    args = get_args()

    # call primary function
    print log_choose(args.n, args.k, args.log)



# initialize the script
if __name__ == '__main__':
    sys.exit(main())
