#!/usr/bin/env python

import argparse, sys
from argparse import RawTextHelpFormatter
from collections import Counter
import math

__author__ = "Colby Chiang (cc2qe@virginia.edu)"
__version__ = "0.0.2"
__date__ = "$Date: 2013-12-07 14:31 $"

# --------------------------------------
# define functions

def get_args():
    parser = argparse.ArgumentParser(formatter_class=RawTextHelpFormatter, description="\
zstats " + __version__ + "\n\
author: " + __author__ + "\n\
description: Calculate basic numeric statistics")
    parser.add_argument('-a', '--abs', action='store_true', help='take absolute values of input before calculating stats')
    parser.add_argument('-p', '--percentile', type=str, default=None, help='comma separated list of percentiles to display')
    parser.add_argument('data', nargs='?', type=argparse.FileType('r'), default=None, help='input column of numbers. (default: stdin)')

    # parse the arguments
    args = parser.parse_args()

    # if no input, check if part of pipe and if so, read stdin.
    if args.data == None:
        if sys.stdin.isatty():
            parser.print_help()
            exit(1)
        else:
            args.data = sys.stdin
    return args

# get the number of entries in the set
def countRecords(myCounter):
    numRecords = sum(myCounter.values())
    return numRecords

# sum of the entries
def sumRecords(myCounter):
    mySum = 0.0
    for c in myCounter:
        mySum += c * float(myCounter[c])
    return mySum

# calculate the arithmetic mean, given a counter and the
# length of the feature (chromosome or genome)
# for x percentile, x% of the elements in the set are
# <= the output value
def mean(myCounter):
    # the number of total entries in the set is the
    # sum of the occurrences for each value
    numRecords = countRecords(myCounter)

    # u holds the mean
    u = float

    u = sumRecords(myCounter) / numRecords
    return u

def stdev(myCounter):
    # the number of total entries in the set is the
    # sum of the occurrences for each value
    numRecords = countRecords(myCounter)

    # u holds the mean
    u = mean(myCounter)
    sumVar = 0.0

    # stdev is sqrt(sum((x-u)^2)/#elements)
    for c in myCounter:
        sumVar += myCounter[c] * (c - u)**2
    myVariance = float(sumVar) / numRecords
    stdev = myVariance**(0.5)
    return stdev

def variance(myCounter):
    # the number of total entries in the set is the
    # sum of the occurrences for each value
    numRecords = countRecords(myCounter)

    # u holds the mean
    u = mean(myCounter)
    sumVar = 0.0

    # stdev is sqrt(sum((x-u)^2)/#elements)
    for c in myCounter:
        sumVar += myCounter[c] * (c - u)**2
    myVariance = float(sumVar) / numRecords
    return myVariance

# the geometric mean is the nth root of the product
# of n values. Here we'll use a logrithmic representation
# so we don't have to deal with rounding error from large
# products.
# geo_mean = exp(arithMean(ln(a_i))
def geoMean(myCounter):
    # if there is a zero in the data, then geometric
    # mean is undefined
    if 0.0 in list(myCounter):
        return 'undef (zero found in data)'

    numRecords = countRecords(myCounter)

    # counter for the log values
    logCounts = Counter()

    # store the log counts 
    for c in myCounter:
        if c < 0:
            return 'undef (negative number found in data)'
        logCounts[math.log(c)] += myCounter[c]
            
    # the mean of the log values
    meanLog = mean(logCounts)

    return math.exp(meanLog)


# calculate percentiles from the depth counter.
# uses the Nearest Rank definition of percentile
def percentile(myCounter, p):
    p = float(p)
    if p <= 0 or p >= 100:
        return
    
    #length is the number of bases we're looking at
    numEntries = countRecords(myCounter)
    # the ordinal value of the output element
    limit = int(round(p/100 * numEntries + 0.5))

    # a list of the values, sorted smallest to largest
    # note that this list contains unique elements only
    valueList = list(myCounter)
    valueList.sort()
    numValues = len(valueList)

    # the number of entries through the set we've gone
    runEntries = 0
    # iterator i
    i = 0
    # initiate v, in case one element in input
    v = valueList [i]

    # move through the value list, iterating by number of
    # entries for each value
    while runEntries < limit:
        v = valueList[i]
        runEntries += myCounter[v]
        i += 1
        # if i is greater than numValues, just return the largest
        if i == (numValues - 1):
            break
    else:
        return v

# median is approx 50th percentile, except when it is between
# two values in which case it's the mean of them.
def median(myCounter):
    #length is the number of bases we're looking at
    numEntries = countRecords(myCounter)

    # the ordinal value of the middle element
    # if 2 middle elements, then non-integer
    limit = 0.5 * numEntries

    # a list of the values, sorted smallest to largest
    # note that this list contains unique elements only
    valueList = list(myCounter)
    valueList.sort()

    # number of entries we've gone through
    runEntries = 0
    # index of the current value in valueList
    i = 0
    # initiate v, in case list only has one element
    v = valueList[i]

    # move through the value list, iterating by number of
    # entries for each value
    while runEntries < limit:
        v = valueList[i]
        runEntries += myCounter[v]
        i += 1
    if runEntries == limit:
        return (v + valueList[i]) / 2.0
    else:
        return v
    
def mode(myCounter):
    return myCounter.most_common()[0]

def antimode(myCounter):
    return myCounter.most_common()[:-2:-1][0]

def minimum(myCounter):
    return min(list(myCounter))

def maximum(myCounter):
    return max(list(myCounter))

# primary function
def calcStats(data, absolute, pTile):
    # Each entry in valueCounts is a value, and its count is
    # the number of instances of that value observed in the dataset.
    # So valueCount[5] is the number of times 5 has been seen in the data.
    valueCounts = Counter()
    
    for line in data:
        lineVal = float(line.strip())
        
        # if absolute flag, then absolutize the lineVal
        if absolute:
            lineVal = abs(lineVal)
        
        # add the lineVal to the counter
        valueCounts[lineVal] += 1
    
    # print the formatted output.
    print 'num records:\t%s' % countRecords(valueCounts)
    print 'sum:\t\t%s' % sumRecords(valueCounts)
    print 'arith. mean:\t%s' % mean(valueCounts)
    print 'geo. mean:\t%s' % geoMean(valueCounts)
    print 'min:\t\t%s' % minimum(valueCounts)
    print 'Q1:\t\t%s' % percentile(valueCounts, 25)
    print 'median:\t\t%s' % median(valueCounts)
    print 'Q3:\t\t%s' % percentile(valueCounts, 75)
    print 'max:\t\t%s' % maximum(valueCounts)
    if pTile:
        for myPtile in pTile.split(','):
            pfloat = float(myPtile)
            print '%s %%tile:\t%s' % (myPtile, percentile(valueCounts, pfloat))
    print 'mode:\t\t%s (N=%s)' % mode(valueCounts)
    print 'anti-mode:\t%s (N=%s)' % antimode(valueCounts)
    print 'stdev:\t\t%s' % stdev(valueCounts)
    print 'variance:\t%s' % variance(valueCounts)

    return

# --------------------------------------
# main function

def main():
    # parse the command line args
    args = get_args()

    # store into global values
    data = args.data
    absolute = args.abs
    pTile = args.percentile
    
    # call primary function
    calcStats(data, absolute, pTile)
    
    # close the file
    data.close()

# initialize the script
if __name__ == '__main__':
    sys.exit(main())
